### ISSUE TITLE
selectindices.php --> Internal Server Error (HTTP500)

### ISSUE THREAD

**Issue by henfri** [linuxserver/docker-diskover#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When opening selectindices.php  (under Admin), the dialog for selecting an Index should open.

## Current Behavior
A page with HTTP Status 500 opens

## Steps to Reproduce
1. Open http://server/selectindices.php
- or -
2. Open the webinterface (http://server/
3. Go to the admin page (http://server/admin.php)
4. Under "diskover indices selected" select "Change"

## Environment
**OS:**      
**CPU architecture:** x86_64      
**How docker service was installed:**      

Via docker-compose.yaml
## Command used to create docker container (run/create/compose/screenshot)
```
version: '2'
services:
  diskover:
    image: linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Berlin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
      - RUN_ON_START=true
      - USE_CRON=true
      - DISKOVER_OPTS=--autotag
    volumes:
      - /srv/Daten/dockerconfig/diskover/diskover:/config
      - /srv/DataPool:/data
    ports:
      - 84:80
      - 9181:9181
      - 9999:9999
    mem_limit: 4096m
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - redis
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - /srv/Daten/dockerconfig/diskover/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - /srv/Daten/dockerconfig/diskover/redis:/data
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-diskover-config: executing...
Initial run of dispatcher in progress
[cont-init.d] 50-diskover-config: exited 0.
[cont-init.d] 60-diskover-web-config: executing...
[cont-init.d] 60-diskover-web-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.


     _/_/_/    _/            _/
    _/    _/        _/_/_/  _/  _/      _/_/    _/      _/    _/_/    _/  _/_/
   _/    _/  _/  _/_/      _/_/      _/    _/  _/      _/  _/_/_/_/  _/_/
  _/    _/  _/      _/_/  _/  _/    _/    _/    _/  _/    _/        _/
 _/_/_/    _/  _/_/_/    _/    _/    _/_/        _/       _/_/_/  _/
                              v1.5.0.10
                              https://shirosaidev.github.io/diskover
                              "I didn't even know that was there."
                              Support diskover on Patreon or PayPal :)


2020-03-21 00:53:46,283 [INFO][diskover] Using config file: /app/diskover/diskover.cfg
/app/diskover/diskover_bot_module.py:883: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if path[3] is 'directory':
2020-03-21 00:53:46,298 [INFO][diskover] Waiting for connection, listening on 0.0.0.0 port 9999 TCP (ctrl-c to shutdown)
RQ Dashboard version 0.6.1
 * Running on 0.0.0.0:9181
 * Serving Flask app "rq_dashboard.cli" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-03-21 14:24:16,043 [INFO][diskover] Got a connection from ('172.19.0.4', 60582)
2020-03-21 14:24:16,044 [INFO][diskover] Waiting for connection, listening on 0.0.0.0 port 9999 TCP (ctrl-c to shutdown)
2020-03-21 14:24:16,044 [INFO][diskover] [thread-0]: Got ping from ('172.19.0.4', 60582)
2020-03-21 14:24:16,044 [INFO][diskover] [thread-0]: ('172.19.0.4', 60582) closed connection
2020-03-21 16:24:42,789 [INFO][diskover] Got a connection from ('172.19.0.4', 47296)
2020-03-21 16:24:42,789 [INFO][diskover] Waiting for connection, listening on 0.0.0.0 port 9999 TCP (ctrl-c to shutdown)
2020-03-21 16:24:42,790 [INFO][diskover] [thread-1]: Got ping from ('172.19.0.4', 47296)
2020-03-21 16:24:42,790 [INFO][diskover] [thread-1]: ('172.19.0.4', 47296) closed connection
2020-03-21 16:24:48,568 [INFO][diskover] Got a connection from ('172.19.0.4', 47322)
2020-03-21 16:24:48,568 [INFO][diskover] Waiting for connection, listening on 0.0.0.0 port 9999 TCP (ctrl-c to shutdown)
2020-03-21 16:24:48,568 [INFO][diskover] [thread-2]: Got ping from ('172.19.0.4', 47322)
2020-03-21 16:24:48,568 [INFO][diskover] [thread-2]: ('172.19.0.4', 47322) closed connection
2020-03-21 16:25:18,099 [INFO][diskover] Got a connection from ('172.19.0.4', 47382)
2020-03-21 16:25:18,099 [INFO][diskover] Waiting for connection, listening on 0.0.0.0 port 9999 TCP (ctrl-c to shutdown)

```

Best regards and thanks for the great containers!

Hendrik
